BOOK_STATUS_OPTIONS_TABLE = {
    100: [{'key': 'edit_metadata', 'text': 'Edit Metadata',
           'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
          {'key': 'delete', 'text': 'Delete',
           'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
          ],
    150: [{'key': 'open', 'text': 'Open', 'icon': 'book_white.png',
           'color': 'blue'},
           {'key': 'retry_metadata', 'text': 'Retry Metadata',
           'icon': 'retry.png', 'color': 'dark_blue'},
          {'key': 'edit_metadata', 'text': 'Edit Metadata',
           'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
          {'key': 'export', 'text': 'Export',
           'icon': 'baseline_import_export_white_48dp.png', 'color': 'blue'},
          {'key': 'delete', 'text': 'Delete',
           'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
          ],

    200: [
        {'key': 'open', 'text': 'Open', 'icon': 'book_white.png',
         'color': 'blue'},
        {'key': 'edit_metadata', 'text': 'Edit Metadata',
         'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'upload', 'text': 'Upload',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'dark_blue'},
        {'key': 'export', 'text': 'Export',
         'icon': 'baseline_import_export_white_48dp.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],

    300: [
        {'key': 'open', 'text': 'Open', 'icon': 'book_white.png',
         'color': 'blue'},
        {'key': 'edit_metadata', 'text': 'Edit Metadata',
         'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'upload', 'text': 'Upload',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'dark_blue'},
        {'key': 'export', 'text': 'Export',
         'icon': 'baseline_import_export_white_48dp.png', 'color': 'blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
        #  'icon': 'nuke_colored_icon.png', 'color': 'red'},
    ],
    400: [
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    401: [
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    419: [
        {'key': 'retry_compression', 'text': 'Retry compression',
         'icon': 'retry.png', 'color': 'dark_blue'},
        {'key': 'package_uncompressed_imgstack', 'text': 'Upload JPEG images',
         'icon': 'ignore_and_continue.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    429: [
        {'key': 'retry_preimage', 'text': 'Retry packaging',
         'icon': 'retry.png', 'color': 'dark_blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],

    458: [{'key': 'open', 'text': 'Open', 'icon': 'camera_white.png',
           'color': 'blue'},
        {'key': 'retry_blur_detection', 'text': 'Retry blur detection', 'icon': 'retry.png',
           'color': 'dark_blue'},
          {'key': 'skip_blur_detection', 'text': 'Ignore and continue', 'icon': 'ignore_and_continue.png',
           'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
          ],
    470: [
        {'key': 'retry_packaging', 'text': 'Retry packaging',
         'icon': 'retry.png', 'color': 'dark_blue'},
         {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    490: [
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    500: [
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    520: [
        {'key': 'retry_upload', 'text': 'Retry upload',
         'icon': 'retry.png', 'color': 'dark_blue'},
        {'key': 'force_upload', 'text': 'Force upload',
         'icon': 'vader.png', 'color': 'blue'},
        {'key': 'retry_preimage', 'text': 'Retry packaging',
         'icon': 'layers_white.png', 'color': 'blue'},
        {'key': 'edit_metadata', 'text': 'Edit Metadata',
           'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    590: [
        {'key': 'move_to_scribing', 'text': 'Back to Scribing',
         'icon': 'go_back.png', 'color': 'blue'},
        {'key': 'upload_done_book_anew', 'text': 'Upload again',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    798: [
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    799: [
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    800: [
        {'key': 'start_corrections', 'text': 'Start corrections',
         'icon': 'baseline_play_circle_filled_white_48dp.png', 'color': 'dark_blue'},
        #{'key': 'edit_metadata', 'text': 'Edit Metadata',
        #'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    801: [
        {'key': 'start_foldouts', 'text': 'Start foldouts',
         'icon': 'baseline_play_circle_filled_white_48dp.png', 'color': 'dark_blue'},
        #{'key': 'edit_metadata', 'text': 'Edit Metadata',
        # 'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    825: [
        {'key': 'open_reshooting_index', 'text': 'Reshooting index',
         'icon': 'log_white.png', 'color': 'blue'},
        #{'key': 'edit_metadata', 'text': 'Edit Metadata',
        # 'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'upload_corrections',
         'text': 'Upload',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'dark_blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    826: [
        {'key': 'open_foldouts', 'text': 'Capture foldouts',
         'icon': 'camera_white.png', 'color': 'blue'},
        #{'key': 'edit_metadata', 'text': 'Edit Metadata',
        # 'icon': 'baseline_edit_white_48dp.png', 'color': 'blue'},
        {'key': 'upload_foldouts',
         'text': 'Upload',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'dark_blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    830: [
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    831: [
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    840: [
        {'key': 'retry_upload_corrections',
         'text': 'Retry',
         'icon': 'retry.png', 'color': 'dark_blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    841: [
        {'key': 'retry_upload_foldouts', 'text': 'Retry',
         'icon': 'retry.png', 'color': 'dark_blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    850: [
        {'key': 'upload_done_book_anew', 'text': 'Upload again',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'dark_blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    888: [
        {'key': 'upload_done_book_anew', 'text': 'Upload again',
         'icon': 'baseline_cloud_upload_white_48dp.png', 'color': 'dark_blue'},
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete', 'text': 'Delete',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},

    ],
    900: [
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
    ],
    901: [
        {'key': 'open_browser', 'text': 'See IA item',
         'icon': 'open_in_browser_white.png', 'color': 'blue'},
        {'key': 'delete_staged', 'text': 'Actually Delete ',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
    ],
    996: [{'key': 'undelete_staged', 'text': 'Back to staging',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'blue'},
         {'key': 'delete_anyway', 'text': 'Delete anyway',
         'icon': 'baseline_delete_white_48dp.png', 'color': 'red'},
          ],

}

BUTTON_COLORS_TABLE = {
    'green': {'color_normal': [0, .8, 0, .6],
              'color_down': [0, .8, 0, 1]},

    'dark_green': {'color_normal': [0, 0.5, 0, .7],
                   'color_down': [0, 0.5, 0, 1]},

    'grey': {'color_normal': [0, 0.28, 0.42, .7],
             'color_down': [0, 0.28, 0.42, 1]},

    'white': {'color_normal': [1, 1, 1, 1],
             'color_down': [1, 1, 1, .5]},

    'transparent': {'color_normal': [1, 1, 1, 0],
             'color_down': [0.05, 0.2, .8, .1]},

    'red': {'color_normal': [0.4, 0.4, 0.4, .7],
            'color_down': [0, 0, 0, .9]},

    'old_dark_blue': {'color_normal': [0, 0, .8, .8],
                  'color_down': [0, 0, .8, 1]},

    'old_blue': {'color_normal': [0, 0, .8, .6],
             'color_down': [0, 0, .8, .8]},

    'dark_blue': {'color_normal': [0.05, 0.2, 0.8, .8],
             'color_down': [0.05, 0.2, .8, 1]},

    'blue': {'color_normal': [0.1, 0.3, 0.8, .7],
             'color_down': [0.1, 0.3, .8, 1]},

    'orange': {'color_normal': [0, 0.7, 0.6, .6],
               'color_down': [0, .7, 0.6, .8]},
}
