from os.path import join, dirname

from kivy.factory import Factory
from kivy.lang import Builder

# Load rules of widgets without Python classes
Builder.load_file(join(dirname(__file__), 'uix', 'widgets','widgets.kv'))

r = Factory.register

r('TopBar', module='ia_scribe.uix.components.toolbars.top_bar')
r('BookMenuBar', module='ia_scribe.uix.components.toolbars.book_menu_bar')
r('LeafMenuBar', module='ia_scribe.uix.components.toolbars.leaf_menu_bar')
r('ImageMenuBar', module='ia_scribe.uix.components.toolbars.image_menu_bar')
r('SpreadMenuBar', module='ia_scribe.uix.components.toolbars.spread_menu_bar')
r('SpreadSliderBar', module='ia_scribe.uix.components.toolbars.spread_slider_bar')
r('ReShootMenuBar', module='ia_scribe.uix.components.toolbars.reshoot_menu_bar')
r('ReShootSliderBar', module='ia_scribe.uix.components.toolbars.reshoot_slider_bar')
r('ColorButton', module='ia_scribe.uix.components.buttons.buttons')
r('ColorToggleButton', module='ia_scribe.uix.components.buttons.buttons')
r('ImageButton', module='ia_scribe.uix.components.buttons.buttons')
r('TooltipImageButton', module='ia_scribe.uix.components.buttons.buttons')
r('TooltipToggleButton', module='ia_scribe.uix.components.buttons.buttons')
r('ImageToggleButton', module='ia_scribe.uix.components.buttons.buttons')
r('TooltipImageToggleButton', module='ia_scribe.uix.components.buttons.buttons')
r('MarkerButton', module='ia_scribe.uix.components.buttons.buttons')
r('SortButton', module='ia_scribe.uix.components.buttons.buttons')
r('SortButtonView', module='ia_scribe.uix.components.buttons.buttons')
r('IconButton', module='ia_scribe.uix.components.buttons.buttons')
r('ToggleIconButton', module='ia_scribe.uix.components.buttons.buttons')
r('RecycleIconButton', module='ia_scribe.uix.components.buttons.buttons')
r('RadioButton', module='ia_scribe.uix.components.buttons.buttons')
r('TooltipIconButton', module='ia_scribe.uix.components.buttons.buttons')
r('TooltipColorButton', module='ia_scribe.uix.components.buttons.buttons')
r('SpinnerColorButton', module='ia_scribe.uix.components.buttons.buttons')
r('LeftAlignedSpinner', module='ia_scribe.uix.components.form.form_inputs')
r('TooltipBehavior', module='ia_scribe.uix.behaviors.tooltip')
r('TooltipControl', module='ia_scribe.uix.behaviors.tooltip')
r('TooltipScreen', module='ia_scribe.uix.behaviors.tooltip')
r('TooltipLabel', module='ia_scribe.uix.components.labels.labels')
r('PageNumLabel', module='ia_scribe.uix.components.labels.labels')
r('BlackLabel', module='ia_scribe.uix.components.labels.labels')
r('CopyLabel', module='ia_scribe.uix.components.labels.labels')
r('RecycleViewLabel', module='ia_scribe.uix.components.labels.labels')
r('CheckBoxLabel', module='ia_scribe.uix.components.labels.labels')
r('ScrollableLabel', module='ia_scribe.uix.components.labels.labels')
r('LeafInfoPanel', module='ia_scribe.uix.screens.capture.leaf_info_panel')
r('LeafInfoPanelItem', module='ia_scribe.uix.screens.capture.leaf_info_panel')
r('NumberInput', module='ia_scribe.uix.components.form.form_inputs')
r('EmailTextInput', module='ia_scribe.uix.components.form.form_inputs')
r('RegexTextInput', module='ia_scribe.uix.components.form.form_inputs')
r('MetadataTextInput', module='ia_scribe.uix.components.form.form_inputs')
r('MetadataSwitch', module='ia_scribe.uix.components.form.form_inputs')
r('KeyInput', module='ia_scribe.uix.components.form.form_inputs')
r('SettingsSwitch', module='ia_scribe.uix.components.form.form_inputs')
r('SettingsInputBox', module='ia_scribe.uix.components.form.form_inputs')
r('TooltipTextInput', module='ia_scribe.uix.components.form.form_inputs')
r('ShortenSpinnerOption', module='ia_scribe.uix.components.form.form_inputs')
r('SpinnerWithLabel', module='ia_scribe.uix.components.form.form_inputs')
r('LeafNoteInput', module='ia_scribe.uix.components.form.form_inputs')
r('FileChooser', module='ia_scribe.uix.components.file_choose.file_chooser')
r('TooltipSlider', module='ia_scribe.uix.components.tooltip_slider')
r('MarkedTooltipSlider', module='ia_scribe.uix.components.tooltip_slider')
r('ImageZoom', module='ia_scribe.uix.screens.capture.image_zoom')
r('UploadScreen', module='ia_scribe.uix.screens.library.upload_screen')
r('SettingsScreen', module='ia_scribe.uix.screens.settings.settings_screen')
r('UserSwitchScreen', module='ia_scribe.uix.screens.user_switch.user_switch_screen')
r('CalibrationScreen', module='ia_scribe.uix.screens.calibration.screen')
r('MetadataScreen', module='ia_scribe.uix.screens.settings.metadata_screen')
r('WizardScreen', module='ia_scribe.uix.screens.wizard.screen')
r('BookMetadataScreen', module='ia_scribe.uix.screens.metadata.book_metadata_screen')
r('ReShootScreen', module='ia_scribe.uix.screens.corrections.reshoot_screen')
r('ReScribeScreen', module='ia_scribe.uix.screens.corrections.rescribe_screen')
r('CaptureScreen', module='ia_scribe.uix.screens.capture.capture_screen')
r('ExtensionsScreen', module='ia_scribe.extensions.extensions_screen')
r('StatsScreen', module='ia_scribe.uix.screens.stats.stats_screen')
r('HelpCenterScreen', module='ia_scribe.uix.screens.help.help_center')
r('CaptureSpread', module='ia_scribe.uix.screens.capture.capture_spread')
r('UploadWidget', module='ia_scribe.uix.screens.library.upload_widget')
r('LibraryView', module='ia_scribe.uix.screens.library.library_view')
r('OverlayView', module='ia_scribe.uix.components.overlay.overlay_view')
r('FoldoutOverlay', module='ia_scribe.uix.screens.capture.foldout_overlay')
r('SortHeader', module='ia_scribe.uix.components.sort_header')
r('NoteLeafsView', module='ia_scribe.uix.screens.corrections.note_leafs_view')
r('BookInfoPanel', module='ia_scribe.uix.screens.corrections.book_info_panel')
r('InfoBox', module='ia_scribe.uix.components.info_box.info_box')
r('SelectableGridLayout', module='ia_scribe.uix.components.layouts')
r('RecycleButtons', module='ia_scribe.uix.components.recycle_buttons')
r('CropBox', module='ia_scribe.uix.components.image_boxes.crop_box')
r('ZoomBox', module='ia_scribe.uix.components.image_boxes.zoom_box')
r('HoverBehavior', module='ia_scribe.uix.behaviors.hover')
